jobs:

- job: Ubuntu

  pool:
    vmImage: 'Ubuntu 16.04' # 'VS2017-Win2016'

  variables: 
     solution: '**/*.sln' 
     buildPlatform: 'Any CPU' 
     buildConfiguration: 'Release' 

  steps:
 
  - script: docker run --name mysql -e 'MYSQL_ROOT_PASSWORD=Password12!' -d mysql:latest
    displayName: 'Run MySql on Linux container'
    
  - script: |
      export AZUREDEV="true"
      export MYSQLIP=docker inspect -f "{{ .NetworkSettings.IPAddress }}" mysql
      printenv
    displayName: 'Inspect docker'

  #- script: |
  #    docker inspect mysql
  #    docker inspect sqlserver  
  #  displayName: 'Inspect docker'

  #- script: docker run --name sqlserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password12!' -p 1433:1433  -d microsoft/mssql-server-linux:2017-latest
  #  displayName: 'Run SQL 2017 on Linux container'

  #- script: |
  #    sqlcmd -S localhost -U SA -P 'Password12!' -Q 'select @@VERSION'
  #    exit
  #  displayName: 'Run SQLCMD'

  - script: dotnet build Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj
    displayName: 'Dotmim.Sync.Core'
  #- script: dotnet build Projects/Dotmim.Sync.SqlServer/Dotmim.Sync.SqlServer.csproj
  #  displayName: 'Dotmim.Sync.SqlServer'
  #- script: dotnet build Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj
  #  displayName: 'Dotmim.Sync.Sqlite'
  #- script: dotnet build Projects/Dotmim.Sync.MySql/Dotmim.Sync.MySql.csproj
  #  displayName: 'Dotmim.Sync.MySql'
  #- script: dotnet build Projects/Dotmim.Sync.Web.Client/Dotmim.Sync.Web.Client.csproj
  #  displayName: 'Dotmim.Sync.Web.Client'
 
  # Because we habe a build on both .Net Standard 2.0 AND .Net 4.6, We just make the build on .Net Standard 2.0
  #- script: dotnet build Projects/Dotmim.Sync.Web.Server/Dotmim.Sync.Web.Server.csproj -f netstandard2.0
  #  displayName: 'Build Dotmim.Sync.Web.Server for .Net Standard 2.0' 
  #
  #- script: dotnet build Projects/dotnet-sync/dotnet-sync.csproj
  #  displayName: 'dotnet-sync'

  #- task: VSTest@2
  #  inputs:
  #    testSelector: 'testAssemblies' # Options: testAssemblies, testPlan, testRun
  #    testAssemblyVer2: 'Tests\Dotmim.Sync.Tests**\*Tests*.dll'